baseURL = "https://EspenBerget.github.io"
languageCode = "en-us"
title = "My New Hugo Site"



# Theme
theme = "paperback"
[params]
AuthorName = "Espen Berget"
HomepagePosts = 5
GithubUsername = "EspenBerget"


