baseURL = "https://EspenBerget.github.io/"
languageCode = "en-us"
title = "Espen Berget's Blog"



# Theme
theme = "paperback"
[params]
AuthorName = "Espen Berget"
HomepagePosts = 5
GithubUsername = "EspenBerget"


